[project]
name = "vector-databases-in-practice-deep-dive-4513162"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "altair==5.2.0",
    "annotated-types==0.6.0",
    "anyio==4.2.0",
    "attrs==23.2.0",
    "authlib==1.3.0",
    "beautifulsoup4==4.12.3",
    "blinker==1.7.0",
    "cachetools==5.3.2",
    "certifi==2023.11.17",
    "cffi==1.16.0",
    "charset-normalizer==3.3.2",
    "click==8.1.7",
    "cryptography==41.0.7",
    "deprecated==1.2.14",
    "exceptiongroup==1.2.0",
    "gitdb==4.0.11",
    "gitpython==3.1.41",
    "grpcio==1.60.0",
    "grpcio-health-checking==1.60.0",
    "grpcio-tools==1.60.0",
    "h11==0.14.0",
    "httpcore==1.0.2",
    "httpx==0.26.0",
    "idna==3.6",
    "importlib-metadata==7.0.1",
    "jinja2==3.1.3",
    "jsonschema==4.20.0",
    "jsonschema-specifications==2023.12.1",
    "markdown-it-py==3.0.0",
    "markupsafe==2.1.3",
    "mdurl==0.1.2",
    "mediawikiapi==1.2",
    "numpy==1.26.3",
    "packaging==23.2",
    "pandas==2.1.4",
    "pillow==10.2.0",
    "protobuf==4.25.2",
    "pyarrow==14.0.2",
    "pycparser==2.21",
    "pydantic>=2.8.0",
    "pydeck==0.8.1b0",
    "pygments==2.17.2",
    "python-dateutil==2.8.2",
    "python-dotenv==1.0.0",
    "pytz==2023.3.post1",
    "referencing==0.32.1",
    "requests==2.31.0",
    "rich==13.7.0",
    "rpds-py==0.17.1",
    "six==1.16.0",
    "smmap==5.0.1",
    "sniffio==1.3.0",
    "soupsieve==2.5",
    "streamlit==1.30.0",
    "tenacity==8.2.3",
    "toml==0.10.2",
    "toolz==0.12.0",
    "tornado==6.4",
    "typing-extensions>=4.12.2",
    "tzdata==2023.4",
    "tzlocal==5.2",
    "urllib3==2.1.0",
    "validators==0.35.0",
    "weaviate-client==4.16.6",
    "wrapt==1.16.0",
    "zipp==3.17.0",
]